# Generated by Django 5.2.17 on 2026-08-26 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school_sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Grade One", "Grade 1"),
                            ("Grade Two", "Grade 2"),
                            ("Grade Three", "Grade 3"),
                            ("Grade Four", "Grade 4"),
                            ("Grade Five", "Grade 5"),
                            ("Grade Six", "Grade 6"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "School Class",
                "verbose_name_plural": "School Classes",
            },
        ),
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_sessions.schoolsession",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.schoolclass",
                    ),
                ),
            ],
        ),
    ]
